export enum ClsType {
	UsersColumn = 'users-column',
	EmailColumn = 'email-column',
	RoleColumn = 'role-column',
	DepartmentColumn = 'department-column',
	ProjectColumn = 'project-column',
	OfficeColumn = 'office-column',
	OptionsColumn = 'options-column',
	CheckAllColumn = 'check-all-column',
	TaskColumn = 'task-column',
	StatusColumn = 'status-column',
	TimeColumn = 'time-column',
	PaidColumn = 'paid-column',
	LinkColumn = 'link-column',
	ViewColumn = 'view-column',
	ApproveColumn = 'approve-column',
	NotesColumn = 'notes-column',
	NameColumn = 'name-column',
}
