import {DepartmentEnum} from '../enums/department.enum';
import {Role} from '../enums/role.enum';
import {IEmployee} from '../interfaces/employee.interface';
import {PROJECT_MOCK} from './project.mock';
import {Department} from '../enums/department.enum';

export const EMPLOYEE_MOCK: IEmployee[] = [
	{
		firstName: 'Disarae',
		secondName: 'Workman',
		projects: [PROJECT_MOCK[0]],
		department: Department.BE,
		role: Role.ADMIN,
		image: 'assets/image/human.jpg',
		department: DepartmentEnum.FE,
	},
	{
		firstName: 'Emery',
		secondName: 'Vetrovs',
		projects: [PROJECT_MOCK[0]],
		department: Department.FE,
		role: Role.MANAGER,
		image: 'assets/image/human.jpg',
		department: DepartmentEnum.Design,
	},
	{
		firstName: 'Marilyn',
		secondName: 'Dokidis',
		projects: [PROJECT_MOCK[0]],
		department: Department.FE,
		role: Role.MANAGER,
		image: 'assets/image/human.jpg',
		department: DepartmentEnum.DWH,
	},
	{
		firstName: 'Martin',
		secondName: 'Botosh',
		projects: [PROJECT_MOCK[0]],
		department: Department.DWH,
		role: Role.EMPLOYEE,
		image: 'assets/image/human.jpg',
		department: DepartmentEnum.BE,
	},
	{
		firstName: 'Wilson',
		secondName: 'George',
		projects: [PROJECT_MOCK[0]],
		department: Department.DESIGN,
		role: Role.EMPLOYEE,
		image: 'assets/image/human.jpg',
		department: DepartmentEnum.QA,
	},
	{
		firstName: 'Workman',
		secondName: 'George',
		projects: [PROJECT_MOCK[0]],
		department: Department.QA,
		role: Role.EMPLOYEE,
		image: 'assets/image/human.jpg',
		department: DepartmentEnum.FE,
	},
	{
		firstName: 'Disarae',
		secondName: 'Workman',
		projects: [PROJECT_MOCK[0]],
		department: Department.DWH,
		role: Role.ADMIN,
		image: 'assets/image/human.jpg',
		department: DepartmentEnum.FE,
	},
	{
		firstName: 'Emery',
		secondName: 'Vetrovs',
		projects: [PROJECT_MOCK[0]],
		department: Department.QA,
		role: Role.MANAGER,
		image: 'assets/image/human.jpg',
		department: DepartmentEnum.FE,
	},
	{
		firstName: 'Marilyn',
		secondName: 'Dokidis',
		projects: [PROJECT_MOCK[0]],
		department: Department.BE,
		role: Role.MANAGER,
		image: 'assets/image/human.jpg',
		department: DepartmentEnum.FE,
	},
	{
		firstName: 'Martin',
		secondName: 'Botosh',
		projects: [PROJECT_MOCK[0]],
		department: Department.FE,
		role: Role.EMPLOYEE,
		image: 'assets/image/human.jpg',
		department: DepartmentEnum.FE,
	},
	{
		firstName: 'Wilson',
		secondName: 'George',
		projects: [PROJECT_MOCK[0]],
		department: Department.DESIGN,
		role: Role.EMPLOYEE,
		image: 'assets/image/human.jpg',
		department: DepartmentEnum.FE,
	},
	{
		firstName: 'Workman',
		secondName: 'George',
		projects: [PROJECT_MOCK[0]],
		department: Department.DWH,
		role: Role.EMPLOYEE,
		image: 'assets/image/human.jpg',
		department: DepartmentEnum.FE,
	},
];
