import {Role} from '../enums/role.enum';
import {IEmployee} from '../interfaces/employee.interface';
import {PROJECT_MOCK} from './project.mock';
import {DepartmentEnum} from '../enums/department.enum';
import {CountryEnum} from '../enums/country.enum';

export const EMPLOYEE_MOCK: IEmployee[] = [
	{
		id: 1,
		userName: 'Disarae Workman',
		projects: [PROJECT_MOCK[0], PROJECT_MOCK[1]],
		role: Role.ADMIN,
		image: 'assets/image/human.jpg',
		email: 'dworkman@datamola.com',
		department: DepartmentEnum.FE,
		office: CountryEnum.Belarus,
		rate: 20,
		salaryReview: new Date(2022, 9, 15),
		dateStart: new Date(2022, 1, 1),
	},
	{
		id: 2,
		userName: 'Emery Vetrovs',
		projects: [PROJECT_MOCK[0]],
		role: Role.MANAGER,
		image: 'assets/image/human.jpg',
		email: 'evetros@datamola.com',
		department: DepartmentEnum.Design,
		office: CountryEnum.Cypris,
		rate: 15,
		salaryReview: new Date(2022, 11, 15),
		dateStart: new Date(2022, 1, 1),
	},
	{
		id: 3,
		userName: 'Marilyn Dokidis',
		projects: [PROJECT_MOCK[2], PROJECT_MOCK[3]],
		role: Role.CTO,
		image: 'assets/image/human.jpg',
		email: 'mdokidis@datamola.com',
		department: DepartmentEnum.DWH,
		office: CountryEnum.USA,
		rate: 30,
		salaryReview: new Date(2022, 9, 10),
		dateStart: new Date(2022, 1, 1),
	},
	{
		id: 4,
		userName: 'Dokidis Marilyn',
		projects: [PROJECT_MOCK[0], PROJECT_MOCK[1]],
		role: Role.CTO,
		image: 'assets/image/human.jpg',
		email: 'mdokidis@datamola.com',
		department: DepartmentEnum.DWH,
		office: CountryEnum.USA,
		rate: 30,
		salaryReview: new Date(2022, 12, 1),
		dateStart: new Date(2021, 6, 1),
	},
	{
		id: 5,
		userName: 'Martin Botosh',
		projects: [PROJECT_MOCK[1]],
		role: Role.EMPLOYEE,
		image: 'assets/image/human.jpg',
		email: 'mbotosh@datamola.com',
		department: DepartmentEnum.FE,
		office: CountryEnum.Belarus,
		rate: 5,
		salaryReview: new Date(2022, 8, 10),
		dateStart: new Date(2022, 5, 1),
	},
	{
		id: 6,
		userName: 'Wilson George',
		projects: [PROJECT_MOCK[1], PROJECT_MOCK[3]],
		role: Role.EMPLOYEE,
		image: 'assets/image/human.jpg',
		email: 'wgeorge@datamola.com',
		department: DepartmentEnum.QA,
		office: CountryEnum.Belarus,
		rate: 5,
		salaryReview: new Date(2022, 9, 10),
		dateStart: new Date(2022, 1, 1),
	},
	{
		id: 7,
		userName: 'Workman George',
		projects: [PROJECT_MOCK[0]],
		role: Role.EMPLOYEE,
		image: 'assets/image/human.jpg',
		email: 'wgeorge@datamola.com',
		department: DepartmentEnum.BE,
		office: CountryEnum.Poland,
		rate: 5,
		salaryReview: new Date(2022, 9, 10),
		dateStart: new Date(2022, 1, 1),
	},
	{
		id: 8,
		userName: 'Disarae Salivan',
		projects: [PROJECT_MOCK[0]],
		role: Role.ADMIN,
		image: 'assets/image/human.jpg',
		email: 'dsalivan@datamola.com',
		department: DepartmentEnum.FE,
		office: CountryEnum.Poland,
		rate: 20,
		salaryReview: new Date(2022, 12, 10),
		dateStart: new Date(2022, 1, 1),
	},
	{
		id: 9,
		userName: 'Emery Vetrovs',
		projects: [PROJECT_MOCK[1]],
		role: Role.MANAGER,
		image: 'assets/image/human.jpg',
		email: 'evtros@datamola.com',
		department: DepartmentEnum.FE,
		office: CountryEnum.Belarus,
		rate: 20,
		salaryReview: new Date(2022, 12, 10),
		dateStart: new Date(2022, 1, 1),
	},
	{
		id: 10,
		userName: 'Marilyn Dokidis',
		projects: [PROJECT_MOCK[2]],
		role: Role.MANAGER,
		image: 'assets/image/human.jpg',
		email: 'mdokidis@datamola.com',
		department: DepartmentEnum.FE,
		office: CountryEnum.Belarus,
		rate: 20,
		salaryReview: new Date(2022, 12, 10),
		dateStart: new Date(2022, 1, 1),
	},
	{
		id: 11,
		userName: 'Martin Botosh',
		projects: [PROJECT_MOCK[0], PROJECT_MOCK[1]],
		role: Role.EMPLOYEE,
		image: 'assets/image/human.jpg',
		email: 'mbotosh@datamola.com',
		department: DepartmentEnum.FE,
		office: CountryEnum.Russia,
		rate: 20,
		salaryReview: new Date(2022, 12, 10),
		dateStart: new Date(2022, 1, 1),
	},
	{
		id: 12,
		userName: 'Wilson George',
		projects: [PROJECT_MOCK[2]],
		role: Role.EMPLOYEE,
		image: 'assets/image/human.jpg',
		email: 'wgeorge@datamola.com',
		department: DepartmentEnum.FE,
		office: CountryEnum.Russia,
		rate: 20,
		salaryReview: new Date(2022, 12, 10),
		dateStart: new Date(2022, 1, 1),
	},
	{
		id: 13,
		userName: 'Workman George',
		projects: [PROJECT_MOCK[3], PROJECT_MOCK[4]],
		role: Role.EMPLOYEE,
		image: 'assets/image/human.jpg',
		email: 'wgeorge@datamola.com',
		department: DepartmentEnum.FE,
		office: CountryEnum.Belarus,
		rate: 20,
		salaryReview: new Date(2022, 12, 10),
		dateStart: new Date(2022, 1, 1),
	},
];
