import {IFinance} from '../interfaces/finance.interface';
import {EMPLOYEE_MOCK} from './employee.mock';

export const FINANCE_MOKCS: IFinance[] = [
	{
		checked: false,
		dateStart: '01.01.12',
		department: EMPLOYEE_MOCK[0].department,
		employee: EMPLOYEE_MOCK[0],
		grossSalary: '1000',
		percent: '50',
		rate: '10',
		salaryReview: '12.12.12',
		time: '4',
		totalTime: '8',
	},
	{
		checked: false,
		dateStart: '01.01.13',
		department: EMPLOYEE_MOCK[1].department,
		employee: EMPLOYEE_MOCK[1],
		grossSalary: '1000',
		percent: '50',
		rate: '10',
		salaryReview: '12.12.12',
		time: '4',
		totalTime: '8',
	},
	{
		checked: false,
		dateStart: '01.01.12',
		department: EMPLOYEE_MOCK[2].department,
		employee: EMPLOYEE_MOCK[2],
		grossSalary: '1000',
		percent: '50',
		rate: '10',
		salaryReview: '12.12.12',
		time: '4',
		totalTime: '8',
	},
	{
		checked: false,
		dateStart: '01.01.12',
		department: EMPLOYEE_MOCK[3].department,
		employee: EMPLOYEE_MOCK[3],
		grossSalary: '1000',
		percent: '50',
		rate: '10',
		salaryReview: '12.12.12',
		time: '4',
		totalTime: '8',
	},
	{
		checked: false,
		dateStart: '01.01.12',
		department: EMPLOYEE_MOCK[4].department,
		employee: EMPLOYEE_MOCK[4],
		grossSalary: '1000',
		percent: '50',
		rate: '10',
		salaryReview: '12.12.12',
		time: '4',
		totalTime: '8',
	},
	{
		checked: false,
		dateStart: '01.01.12',
		department: EMPLOYEE_MOCK[5].department,
		employee: EMPLOYEE_MOCK[5],
		grossSalary: '1000',
		percent: '50',
		rate: '10',
		salaryReview: '12.12.12',
		time: '4',
		totalTime: '8',
	},
	{
		checked: false,
		dateStart: '01.01.12',
		department: EMPLOYEE_MOCK[6].department,
		employee: EMPLOYEE_MOCK[6],
		grossSalary: '1000',
		percent: '50',
		rate: '10',
		salaryReview: '12.12.12',
		time: '4',
		totalTime: '8',
	},
	{
		checked: false,
		dateStart: '01.01.12',
		department: EMPLOYEE_MOCK[7].department,
		employee: EMPLOYEE_MOCK[7],
		grossSalary: '1000',
		percent: '50',
		rate: '10',
		salaryReview: '12.12.12',
		time: '4',
		totalTime: '8',
	},
	{
		checked: false,
		dateStart: '01.01.12',
		department: EMPLOYEE_MOCK[8].department,
		employee: EMPLOYEE_MOCK[8],
		grossSalary: '1000',
		percent: '50',
		rate: '10',
		salaryReview: '12.12.12',
		time: '4',
		totalTime: '8',
	},
	{
		checked: false,
		dateStart: '01.01.12',
		department: EMPLOYEE_MOCK[9].department,
		employee: EMPLOYEE_MOCK[9],
		grossSalary: '1000',
		percent: '50',
		rate: '10',
		salaryReview: '12.12.12',
		time: '4',
		totalTime: '8',
	},
	{
		checked: false,
		dateStart: '01.01.12',
		department: EMPLOYEE_MOCK[10].department,
		employee: EMPLOYEE_MOCK[10],
		grossSalary: '1000',
		percent: '50',
		rate: '10',
		salaryReview: '12.12.12',
		time: '4',
		totalTime: '8',
	},
	{
		checked: false,
		dateStart: '01.01.12',
		department: EMPLOYEE_MOCK[11].department,
		employee: EMPLOYEE_MOCK[11],
		grossSalary: '1000',
		percent: '50',
		rate: '10',
		salaryReview: '12.12.12',
		time: '4',
		totalTime: '8',
	},
	{
		checked: false,
		dateStart: '01.01.12',
		department: EMPLOYEE_MOCK[12].department,
		employee: EMPLOYEE_MOCK[12],
		grossSalary: '',
		percent: '50',
		rate: '10',
		salaryReview: '12.12.12',
		time: '4',
		totalTime: '168',
	},
];
