import {Status} from '../enums/status.enum';
import {ITask} from '../interfaces/task.interface';
import {PROJECT_MOCK} from './project.mock';

export const TASKS_MOCK: ITask[] = [
	{
		date: new Date(2022, 5, 30),
		checked: false,
		title: 'Feature day table components',
		project: PROJECT_MOCK[0],
		status: Status.Done,
		time: 4,
		overtime: 0,
		paid: false,
		asanaLink: '',
		bitbucketLink: '',
	},
	{
		date: new Date(2022, 6, 4),
		checked: false,
		title: 'Meetings',
		project: PROJECT_MOCK[2],
		status: Status.Done,
		time: 1,
		overtime: 0,
		paid: false,
		asanaLink: '',
		bitbucketLink: '',
	},
	{
		date: new Date(2022, 6, 4),
		checked: false,
		title: 'Code refactoring',
		project: PROJECT_MOCK[2],
		status: Status.Done,
		time: 2,
		overtime: 0,
		paid: false,
		asanaLink: '',
		bitbucketLink: '',
	},
	{
		date: new Date(2022, 6, 4),
		checked: false,
		title: 'Add global styles for mat-button',
		project: PROJECT_MOCK[2],
		status: Status.Done,
		time: 5,
		overtime: 0,
		paid: false,
		asanaLink: '',
		bitbucketLink: '',
	},
	{
		date: new Date(2022, 6, 5),
		checked: false,
		title: 'Add Left panel (svg logos inside)',
		project: PROJECT_MOCK[2],
		status: Status.Done,
		time: 10,
		overtime: 2,
		paid: true,
		asanaLink: '',
		bitbucketLink: '',
	},
	{
		date: new Date(2022, 6, 15),
		checked: false,
		title: 'Feature page wrapper',
		project: PROJECT_MOCK[2],
		status: Status.Done,
		time: 5,
		overtime: 2,
		paid: true,
		asanaLink: '',
		bitbucketLink: '',
	},
	{
		date: new Date(2022, 6, 15),
		checked: false,
		title: 'Add fonts',
		project: PROJECT_MOCK[2],
		status: Status.Done,
		time: 3,
		overtime: 0,
		paid: false,
		asanaLink: '',
		bitbucketLink: '',
	},
	{
		date: new Date(2022, 5, 30),
		checked: false,
		title: 'Improve readme (remove tests info)',
		project: PROJECT_MOCK[2],
		status: Status.Done,
		time: 7,
		overtime: 2,
		paid: true,
		asanaLink: '',
		bitbucketLink: '',
	},
	{
		date: new Date(2022, 5, 29),
		checked: false,
		title: 'Add Input Search Focused component',
		project: PROJECT_MOCK[0],
		status: Status.InProgress,
		time: 4,
		overtime: 0,
		paid: false,
		asanaLink: '',
		bitbucketLink: '',
	},
	{
		date: new Date(2022, 5, 29),
		checked: false,
		title: 'Add variasbles',
		project: PROJECT_MOCK[0],
		status: Status.InProgress,
		time: 4,
		overtime: 0,
		paid: false,
		asanaLink: '',
		bitbucketLink: '',
	},
	{
		date: new Date(2022, 6, 13),
		checked: false,
		title: 'Add colors to root',
		project: PROJECT_MOCK[1],
		status: Status.Done,
		time: 2,
		overtime: 0,
		paid: false,
		asanaLink: '',
		bitbucketLink: '',
	},
	{
		date: new Date(2022, 6, 13),
		checked: false,
		title: 'Fix day table components',
		project: PROJECT_MOCK[2],
		status: Status.InProgress,
		time: 2,
		overtime: 0,
		paid: false,
		asanaLink: '',
		bitbucketLink: '',
	},
	{
		date: new Date(2022, 6, 13),
		checked: false,
		title: 'Add Header',
		project: PROJECT_MOCK[2],
		status: Status.InProgress,
		time: 2,
		overtime: 0,
		paid: false,
		asanaLink: '',
		bitbucketLink: '',
	},
	{
		date: new Date(2022, 6, 14),
		checked: false,
		title: 'Vacation',
		project: PROJECT_MOCK[4],
		status: Status.Done,
		time: 8,
		overtime: 0,
		paid: false,
		asanaLink: '',
		bitbucketLink: '',
	},
	{
		date: new Date(2022, 6, 6),
		checked: false,
		title: 'Meetings',
		project: PROJECT_MOCK[2],
		status: Status.Done,
		time: 2,
		overtime: 0,
		paid: false,
		asanaLink: '',
		bitbucketLink: '',
	},
	{
		date: new Date(2022, 6, 6),
		checked: false,
		title: 'Code refactoring',
		project: PROJECT_MOCK[2],
		status: Status.Done,
		time: 2,
		overtime: 0,
		paid: false,
		asanaLink: '',
		bitbucketLink: '',
	},
	{
		date: new Date(2022, 6, 7),
		checked: false,
		title: 'Vacation',
		project: PROJECT_MOCK[4],
		status: Status.Done,
		time: 8,
		overtime: 8,
		paid: true,
		asanaLink: '',
		bitbucketLink: '',
	},
	{
		date: new Date(2022, 6, 8),
		checked: false,
		title: 'Vacation',
		project: PROJECT_MOCK[4],
		status: Status.Done,
		time: 8,
		overtime: 8,
		paid: true,
		asanaLink: '',
		bitbucketLink: '',
	},
	{
		date: new Date(2022, 6, 11),
		checked: false,
		title: 'Vacation',
		project: PROJECT_MOCK[4],
		status: Status.Done,
		time: 8,
		overtime: 8,
		paid: true,
		asanaLink: '',
		bitbucketLink: '',
	},
	{
		date: new Date(2022, 6, 12),
		checked: false,
		title: 'Vacation',
		project: PROJECT_MOCK[4],
		status: Status.Done,
		time: 8,
		overtime: 8,
		paid: true,
		asanaLink: '',
		bitbucketLink: '',
	},
];
